- name: openrouter/deepseek-ai/deepseek-coder-33b-instruct
  extra_params:
    extra_body:
      provider:
        # Prioritize DeepSeek for best value for money
        order: ["DeepSeek"]
        # Don't fall back to other providers
        allow_fallbacks: false
        # Skip providers that may train on inputs
        data_collection: "deny"
        # Only use providers supporting all parameters
        require_parameters: true
