#!/usr/bin/env bash
set -euo pipefail
# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"

require rm sqlcheck tee

declare -i exitCode=0

rm -f ./check.errors || {
  echo "Error removing check.errors"
  exit 1
}

for f in *.sql; do
  [[ -e "$f" ]] || continue
  sqlcheck -c -v -f "$f" | tee -a check.errors
  ((exitCode |= $?))
done

exit "$exitCode"
