#!/usr/bin/env bash
# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"

require psql

if [ $# -ne 1 ]; then
  echo "usage: $0 db"
  echo "db - database name"
  exit 1
fi
db="$1"
# Open your database
psql "$db"
exit $?
