#!/usr/bin/env bash
set -euo pipefail
shopt -s inherit_errexit

# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"

require mvn
function usage() {
  echo "Usage: $0 projName packageName"
  exit 1
}
if [ $# -ne 2 ]; then
  usage
fi
projName="$1"
packageName="$2"
mvn archetype:generate -DgroupId="$packageName" \
  -DartifactId="$projName" \
  -DarchetypeArtifactId=maven-archetype-quickstart \
  -DarchetypeVersion=1.4 \
  -DinteractiveMode=false
exit $?
