#!/usr/bin/env bash
# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"

require npm npx
function usage() {
  echo "Usage: $0 projName"
  exit 1
}
if [ $# -ne 1 ]; then
  usage
fi
mkdir "$1"
cd "$1" || exit
npm init -y
npm install --save-dev assemblyscript
npx asinit -y .
npm run asbuild
npm test
# npm start
