#!/usr/bin/env bash
set -euo pipefail
# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"

require sqlite3
if [ "$#" -ne 3 ]; then
  echo "$0 db script"
  echo "db - database name"
  echo "script - sql script"
  exit 1
fi
db="$1"
script="$2"
sqlite3 "$db" < "$script"
exit "$?"
