#!/usr/bin/env bash
set -euo pipefail
# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"

require psql
if [ "$#" -ne 3 ]; then
  echo "$0 host db script"
  echo "host - host name or ip address"
  echo "db - database name"
  echo "script - sql script"
  exit 1
fi
host="$1"
db="$2"
script="$3"
psql -U u0_a286 -h "$host" -d "$db" -f "$script" -a
exit "$?"
