#!/usr/bin/env bash

######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitalias
# @created     : Friday Jan 27, 2023 04:55:00 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description :
######################################################################

# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"

set -euo pipefail
require git

if ! output=$(git config --get-regexp '^alias\.'); then
  echo "Error retrieving Git aliases" >&2
  exit 1
fi

printf "%s\n" "$output"
