#!/usr/bin/env bash
######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitadd
# @created     : Tuesday Feb 8, 2022 08:00:00 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description : Add all changes to git staging area and show status
######################################################################
set -euo pipefail
shopt -s inherit_errexit
# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"

# shellcheck source=/dev/null
source "${HOME}/.gitrc"

# Ensure git and hub are available
require git hub

# Add all files to staging area
git add .

if git diff --cached --quiet; then
  echo "No files added."
else
  # Show current git status
  echo "Successfully added files to staging area."
  git status
fi
exit 0
