#!/usr/bin/env bash
# Active hooks
# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"
require npx
npx husky install
# Add hook
npx husky add .husky/commit-msg "npx --no -- commitlint --edit $1"
