#!/usr/bin/env bash
set -euo pipefail
shopt -s inherit_errexit
# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"

parentpath="$(dirname "$(readlink -f "$0")")"

if [[ -e "${parentpath}/internet.sh" ]]; then
  # shellcheck disable=SC1091
  source "${parentpath}/internet.sh"
fi

require gh

if [[ $# -lt 1 ]]; then
  echo "Error: repository not specified" >&2
  exit 1
fi

if ! gh repo clone "$@"; then
  echo "Error cloning repository" >&2
  exit 1
fi
