#!/usr/bin/env bash

# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"

set -e
require git

if [[ $# -lt 1 ]]; then
  printf "usage: %s searchstring\n" "$0"
  exit 1
fi

if ! git log --all --grep="$1"; then
  printf "Error searching Git log\n" >&2
  exit 1
fi

exit 0
