#!/usr/bin/env bash
######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitit
# @created     : Friday Feb 11, 2022 08:00:00 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description : Automates git add, commit, and push operations
######################################################################
set -euo pipefail
shopt -s inherit_errexit
parentpath="$(dirname "$(readlink -f "$0")")"

if [[ -e "${parentpath}/internet.sh" ]]; then
  # shellcheck disable=SC1091
  source "${parentpath}/internet.sh"
fi

gitadd && gitcommit && gitpush

exit 0
