#!/usr/bin/env bash
######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitlastcommit
# @created     : Thursday Dec 15, 2022 07:43:00 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description :
######################################################################

# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"

set -e
require git

if ! output=$(git log -n 1); then
  echo "Error retrieving last Git commit" >&2
  exit 1
fi

printf "%s\n" "$output"
