#!/usr/bin/env bash
######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitpush
# @created     : Thursday May 02, 2019 21:07:57 IST
# @copyright   : Copyright (c) Linus Fernandes
# @description : Sync and push Git branches using merge strategy
######################################################################
# shellcheck disable=SC1090,SC1091,SC2317
set -euo pipefail
shopt -s inherit_errexit
RED="\033[0;31m"
NC="\033[0m" # No Color

if [[ "$#" -gt 0 && "$1" == "--debug" ]]; then
  set -x
  shift
fi

function message() {
  local ret=$1
  if [ "$ret" -eq 0 ]; then
    git diff development main
    git gc
  else
    echo -e "${RED}Returning to branch development${NC}"
    git switch development || exit 1
  fi
  exit "$ret"
}

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
source "$SCRIPT_DIR/require.sh"

parentpath="$(dirname "$0")"
if test -e "${parentpath}/internet.sh"; then
  source "${parentpath}/internet.sh"
fi

require git

mainBranch="main"

trap 'ret=$?; message $ret' EXIT

git pull

if ! git show-ref --quiet refs/heads/development; then
  printf "Local branch development does not exist. Creating it ...\n"
  git checkout -b development
fi

git push origin development

git switch "$mainBranch"
git merge development
git pull
git push origin "$mainBranch"

git switch development
git merge "$mainBranch"
git push origin development

exit 0
