#!/usr/bin/env bash
######################################################################
# @author      : Linus Fernandes (linusfernandes@gmail.com)
# @file        : gitpush
# @created     : Thursday May 02, 2019 21:07:57 IST
# @modified    : Updated with improved error handling and safety measures
# @copyright   : Copyright (c) Linus Fernandes
# @description : Script to push changes to the development branch safely
######################################################################
set -euo pipefail
shopt -s inherit_errexit
# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"

if [[ -e "${SCRIPT_DIR}/internet.sh" ]]; then
  # shellcheck disable=SC1091
  source "${SCRIPT_DIR}/internet.sh"
fi

require git

RED="\033[0;31m"
GREEN="\033[0;32m"
NC="\033[0m" # No Color

command="git push -u origin development"
trap message EXIT

function message() {
  local ret=$?
  if [[ "$ret" -eq 0 ]]; then
    echo -e "${GREEN}✅ Successfully exited with code $ret from last command: $command${NC}"
    if [[ "$(git rev-parse development)" != "$(git rev-parse main)" ]]; then
      git diff development main
    fi
    git gc
  else
    echo -e "${RED}❌ Error: Exit $ret from last command: $command${NC}"
    echo -e "${RED}Returning to branch development...${NC}"
    git checkout development || echo -e "${RED}Failed to switch back to development branch.${NC}"
  fi
  exit "$ret"
}

$command
