#!/usr/bin/env bash
set -euo pipefail
shopt -s inherit_errexit
# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"

require git

# Get the root directory of the Git repository
if ! root=$(git rev-parse --show-toplevel 2> /dev/null); then
  echo "Error: Not a Git repository. Exiting..."
  exit 1
fi

echo "$root"
exit 0
