#!/usr/bin/env bash
set -euo pipefail

# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"
require git

# Check if inside a Git repository
if ! git rev-parse --is-inside-work-tree > /dev/null 2>&1; then
  echo "Error: Not a Git repository. Exiting..."
  exit 1
fi

# Run git log with optional arguments
git log --patch "$@"

exit 0
