#!/usr/bin/env bash
set -euo pipefail
# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"

require find

find . -maxdepth 1 -type f ! -name '*.*' -printf '%f\n'
