#!/usr/bin/env bash

# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"

# Ensure necessary commands are available
require find xargs basename shch

# Find all .out files and process them with shch
# shellcheck disable=SC2016
find . -name "*.out" -print0 \
  | xargs -0 --no-run-if-empty -I '{}' bash -c 'shch "$(basename "{}" .out)"'
