#!/usr/bin/env bash

# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"

# Ensure mariadb-safe is installed
require mariadb-safe

# Start MariaDB in the background
mariadb-safe -u root &

# Optional: Provide a message indicating success
echo "MariaDB is starting..."
