#!/usr/bin/env bash
set -euo pipefail
# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"

require pg_ctl

PG_DATA_DIR="${PREFIX}/var/lib/postgresql"

echo "Stopping PostgreSQL server..."
exec pg_ctl -D "$PG_DATA_DIR" stop
