#!/usr/bin/env bash
# unpack: Extract common file formats
set -euo pipefail
shopt -s inherit_errexit
# Display usage if no parameters given
if [[ $# -eq 0 ]]; then
  echo "Usage: ${0##*/} <archive(s)> - extract common file formats"
  exit 1
fi

# Source the require.sh file
SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
# shellcheck disable=SC1091
source "$SCRIPT_DIR/require.sh"

# Required programs
require 7z unrar unzip tar bunzip2 ar gunzip uncompress

# Loop through provided files
for f in "$@"; do
  if [[ ! -f "$f" ]]; then
    echo "Error: File '$f' does not exist."
    continue
  fi

  echo "Extracting '$f'..."
  case "$f" in
    *.7z) 7z x "$f" ;;
    *.tar.bz2 | *.tbz2) tar xvjf "$f" ;;
    *.bz2) bunzip2 "$f" ;;
    *.deb) ar vx "$f" ;;
    *.tar.gz | *.tgz) tar xvzf "$f" ;;
    *.gz) gunzip "$f" ;;
    *.tar.xz) tar xvf "$f" ;;
    *.tar) tar xvf "$f" ;;
    *.rar) unrar x "$f" ;;
    *.zip) unzip "$f" ;;
    *.Z) uncompress "$f" ;;
    *) echo "Error: Unsupported file format for '$f'" ;;
  esac
done
